when:
  - event: ["manual", "push"]
    branch: ["main"]

engine: nixery

dependencies:
  nixpkgs:
    - nodejs
    - typst

environment:
  ASTRO_TELEMETRY_DISABLED: 1

steps:
  - name: Build Site
    command: |
      echo "Building Site"
      npm run build
      echo "Done! Yay :)"

